name: Variable Scope Demo

# Workflow-Level Variable
env:
  MY_VARIABLE: "I am from the WORKFLOW level"

on:
  push:
    branches:
      - main

jobs:
  scope-demo:
    name: Workflow vs Step Scope
    runs-on: ubuntu-latest

    steps:
      - name: Print Workflow-Level Variable
        run: |
          echo "MY_VARIABLE: $MY_VARIABLE"

      - name: Override with Step-Level Variable
        env:
          MY_VARIABLE: "I am from the STEP level. Overrinding workflow variable"
        run: |
          echo "MY_VARIABLE: $MY_VARIABLE"
